#!/usr/bin/env node
/* Pre-renders each lessons/*.md into HTML using the same renderer the
 * browser uses (assets/js/markdown.js), then writes assets/js/lessons.js
 * exporting LESSONS = { "<module-id>": "<html>" }.
 *
 * Run after editing any lesson markdown:
 *   node scripts/build-lessons.js
 */

const fs = require("fs");
const path = require("path");
const vm = require("vm");

const ROOT = path.resolve(__dirname, "..");
const LESSONS_DIR = path.join(ROOT, "lessons");
const CURRICULUM_PATH = path.join(ROOT, "assets/js/curriculum.js");
const MARKDOWN_PATH = path.join(ROOT, "assets/js/markdown.js");
const OUT_PATH = path.join(ROOT, "assets/js/lessons.js");

const sandbox = {};
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(MARKDOWN_PATH, "utf8"), sandbox);
const renderMarkdown = sandbox.renderMarkdown;
if (typeof renderMarkdown !== "function") {
  console.error("Could not load renderMarkdown from", MARKDOWN_PATH);
  process.exit(1);
}

const curriculumSrc = fs.readFileSync(CURRICULUM_PATH, "utf8");
// Module IDs follow the m##- prefix; setup-item ids don't, so this skips nesting.
const moduleRegex = /id:\s*"(m\d+-[^"]+)"[\s\S]*?lesson:\s*"([^"]+)"/g;
const pairs = [];
let mm;
while ((mm = moduleRegex.exec(curriculumSrc)) !== null) {
  pairs.push({ id: mm[1], lessonPath: mm[2] });
}
if (!pairs.length) {
  console.error("No modules found in", CURRICULUM_PATH);
  process.exit(1);
}

const out = [];
out.push("/* AUTO-GENERATED by scripts/build-lessons.js. Do not edit by hand. */");
out.push("/* Source: lessons/*.md rendered via assets/js/markdown.js. */");
out.push("const LESSONS = {");
for (const { id, lessonPath } of pairs) {
  const abs = path.join(ROOT, lessonPath);
  if (!fs.existsSync(abs)) {
    console.error("Missing lesson file:", abs);
    process.exit(1);
  }
  const md = fs.readFileSync(abs, "utf8");
  const html = renderMarkdown(md);
  out.push(`  ${JSON.stringify(id)}: ${JSON.stringify(html)},`);
  console.log(`  rendered ${id} <- ${lessonPath} (${html.length} chars)`);
}
out.push("};");
out.push("");

fs.writeFileSync(OUT_PATH, out.join("\n"));
console.log(`\nWrote ${OUT_PATH} with ${pairs.length} lessons.`);
